version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: dpc_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /c/data/mysql:/var/lib/mysql