version: '3.1'

services:
  db:
    image: mysql
    container_name: dpc_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
#    volumes:
#      - /my/own/datadir:/var/lib/mysql