version: '3'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    container_name: bitnamiredis
    deploy:
      placement:
        constraints: [node.role == manager]
#      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - '6380:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    volumes:
      - 'c:/data/redis:/bitnami'